### ISSUE TITLE
Activity opens to black canvas

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/ball-and-brick-activity#21]
Activity currently opens to a black canvas.

**Comment by jriyyya** [comment]
I was never able to reproduce it, Tried with starting it through ring as well.

@Dimi20cen @sourabhaa Can you please check if you can reproduce it.

**Comment by Dimi20cen** [comment]
It opens normally for me, tested on sugar live-build, pygame 1.9.4.post1.

**Comment by chimosky** [comment]
I'm running pygame 2.5.0 and this is what happens;

[Screencast from 2023-09-06 13-44-59.webm](https://github.com/sugarlabs/ball-and-brick-activity/assets/16203834/52f9d8f6-d21f-41e3-b6ac-d87c1ae0d62d)

**Comment by Dimi20cen** [comment]
I've update to pygame 2.4.0 and the issue of black canvas is present. @jriyyya, I would suggest updating to a newer version of pygame to be able to reproduce the issue.

Removing 
```
if event.type == pygame.VIDEORESIZE:
    pygame.display.set_mode(event.size, pygame.RESIZABLE)
```
from the `while True:` loop inside the `run` method of class `BallAndBrick` in #20 and i nthe code of the master branch, fixes the black canvas, but might introduce other issues.

**Comment by chimosky** [comment]
> I've update to pygame 2.4.0 and the issue of black canvas is present. @jriyyya, I would suggest updating to a newer version of pygame to be able to reproduce the issue.
> 
> Removing
> 
> ```
> if event.type == pygame.VIDEORESIZE:
>     pygame.display.set_mode(event.size, pygame.RESIZABLE)
> ```
> 
> from the `while True:` loop inside the `run` method of class `BallAndBrick` in #20 and i nthe code of the master branch, fixes the black canvas, but might introduce other issues.

Seems we'll need to reconsider our use of `VIDEORESIZE` according to [pygame](https://www.pygame.org/docs/ref/event.html), could you test your fix and see if any thing is affected and open a PR. Thanks!

**Comment by Dimi20cen** [comment]
From what I understand those lines are not doing anything. Hopefully I dont miss something. Openned PR #22
